name: order_simulator
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.22
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.2.1
  uuid: ^4.4.0
  intl: ^0.19.0
  csv: ^6.0.0
  pdf: ^3.10.8 # Adicionado para gerar PDFs
  printing: ^5.12.0 # Adicionado para a impressão

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Garante que todas as imagens são incluídas
    - assets/csv/ # Garante que os CSVs são incluídos
