class CampanhaPromocional {
  final String categoria;
  final String titulo;
  final String promocode;
  final List<ItemCampanha> itens;
  final double valorFinal;
  final String? observacao;
  final bool destaque;

  CampanhaPromocional({
    required this.categoria,
    required this.titulo,
    required this.promocode,
    required this.itens,
    required this.valorFinal,
    this.observacao,
    this.destaque = false,
  });
}

class ItemCampanha {
  final String codigo;
  final int quantidade;
  final String descricao;
  final double valorUnitario;
  final double desconto;
  final double valorFinal;
  final bool isGratis;

  ItemCampanha({
    required this.codigo,
    required this.quantidade,
    required this.descricao,
    required this.valorUnitario,
    required this.desconto,
    required this.valorFinal,
    this.isGratis = false,
  });
}

// Dados das campanhas hardcoded
final List<CampanhaPromocional> campanhasNeodent = [
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 20 implantes e Ganhe 20 implantes + 2 KIT VPS",
    promocode: "4400676910",
    valorFinal: 8340.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 8340.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "184.182",
        quantidade: 2,
        descricao: "Kit Neodent VPS 600mL + Light (GRÁTIS)",
        valorUnitario: 471.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 20 implantes e Ganhe 20 implantes + 3 brocas",
    promocode: "4400676910",
    valorFinal: 8340.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 8340.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "103.170",
        quantidade: 2,
        descricao: "BROCA LANCA PLUS (GRÁTIS)",
        valorUnitario: 135.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "103.425",
        quantidade: 2,
        descricao: "BROCA CONICA 2.0 (GRÁTIS)",
        valorUnitario: 165.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "103.561",
        quantidade: 2,
        descricao: "BROCA CONICA 3.5 (GRÁTIS)",
        valorUnitario: 165.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 20 implantes e Ganhe 20 implantes + 10 escovas BlueM",
    promocode: "4400676910",
    valorFinal: 8340.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 8340.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "ESCOVA-N",
        quantidade: 10,
        descricao: "ESCOVA ROXA NEODENT (GRÁTIS)",
        valorUnitario: 42.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 20 implantes e Ganhe 20 implantes + Kit BlueM",
    promocode: "4400676910",
    valorFinal: 8340.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 8340.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "OFI250",
        quantidade: 3,
        descricao: "FLUIDO BUCAL BLUEM 250 ML (GRÁTIS)",
        valorUnitario: 76.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "OGS9",
        quantidade: 3,
        descricao: "GEL ORAL BLUEM C/ 3 SERINGAS 9G (GRÁTIS)",
        valorUnitario: 88.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre R\$ 11.000 em componentes protéticos e ganhe 55% de desconto",
    promocode: "4400677010",
    valorFinal: 11144.00,
    itens: [
      ItemCampanha(
        codigo: "108.022",
        quantidade: 15,
        descricao: "TRANSFER MINI P.CONICO MOLD.ABERTA 4.1",
        valorUnitario: 59.00,
        desconto: 0.0,
        valorFinal: 885.00,
      ),
      ItemCampanha(
        codigo: "118.305",
        quantidade: 15,
        descricao: "CILIN.PROVISORIO MUN.UNIV.CLICK 3.3X6",
        valorUnitario: 30.00,
        desconto: 0.0,
        valorFinal: 450.00,
      ),
      ItemCampanha(
        codigo: "115.275",
        quantidade: 23,
        descricao: "MINI PILAR CONICO GM 17 PARAFUSO REM 1.5",
        valorUnitario: 300.00,
        desconto: 0.0,
        valorFinal: 6900.00,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre R\$ 25k em componentes protéticos e ganhe 60% de desconto",
    promocode: "4400677110",
    valorFinal: 25155.00,
    itens: [
      ItemCampanha(
        codigo: "108.022",
        quantidade: 45,
        descricao: "TRANSFER MINI P.CONICO MOLD.ABERTA 4.1",
        valorUnitario: 59.00,
        desconto: 0.0,
        valorFinal: 2655.00,
      ),
      ItemCampanha(
        codigo: "118.305",
        quantidade: 45,
        descricao: "CILIN.PROVISORIO MUN.UNIV.CLICK 3.3X6",
        valorUnitario: 30.00,
        desconto: 0.0,
        valorFinal: 1350.00,
      ),
      ItemCampanha(
        codigo: "115.275",
        quantidade: 42,
        descricao: "MINI PILAR CONICO GM 17 PARAFUSO REM 1.5",
        valorUnitario: 300.00,
        desconto: 0.0,
        valorFinal: 12600.00,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 60 implantes com 50% de desconto e ganhe 2 Kits",
    promocode: "4400606510",
    valorFinal: 12510.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 60,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 50.0,
        valorFinal: 12510.00,
      ),
      ItemCampanha(
        codigo: "BRKITNDT31",
        quantidade: 1,
        descricao: "Kit Protético GM (GRÁTIS)",
        valorUnitario: 2386.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "110.303",
        quantidade: 1,
        descricao: "KIT CIRURGICO COMPACTO HELIX GM COMPLETO (GRÁTIS)",
        valorUnitario: 5818.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 25 mini pilar GM com 35% de desconto",
    promocode: "4400677210",
    valorFinal: 4875.00,
    observacao: "Ganhe 1 kit Neoconvert™ + 3 kit de Reposição",
    itens: [
      ItemCampanha(
        codigo: "115.275",
        quantidade: 25,
        descricao: "MINI PILAR CONICO GM 17 PARAFUSO REM 1.5",
        valorUnitario: 300.00,
        desconto: 35.0,
        valorFinal: 4875.00,
      ),
      ItemCampanha(
        codigo: "BRKITNDT86",
        quantidade: 1,
        descricao: "KIT NEOCONVERT (GRÁTIS)",
        valorUnitario: 1619.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "118.408",
        quantidade: 3,
        descricao: "CILIN. M. PILAR NEOCONVERT 5.0 (5UN), TI (GRÁTIS)",
        valorUnitario: 105.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 120 implantes e Ganhe 120 implantes + 120 intermediários + 1 KIT Cirúrgico",
    promocode: "4400678910",
    valorFinal: 50040.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 120,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 50040.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 120,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "115.243",
        quantidade: 120,
        descricao: "MINI PILAR CONICO GM ALT. 0.8 (GRÁTIS)",
        valorUnitario: 224.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "110.303",
        quantidade: 1,
        descricao: "KIT CIRURGICO COMPACTO HELIX GM COMPLETO (GRÁTIS)",
        valorUnitario: 5818.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 20 implantes Zigoma S e 15 intermediários com 40% de desconto",
    promocode: "4400677310",
    valorFinal: 15792.00,
    observacao: "Ganhe 1 KIT Cirúrgico Zigoma S",
    itens: [
      ItemCampanha(
        codigo: "109.1086",
        quantidade: 20,
        descricao: "IMPLANTE ZYGOMA-S GM 3.5X30",
        valorUnitario: 1092.00,
        desconto: 40.0,
        valorFinal: 13104.00,
      ),
      ItemCampanha(
        codigo: "115.243",
        quantidade: 20,
        descricao: "MINI PILAR CONICO GM ALT. 0.8",
        valorUnitario: 224.00,
        desconto: 40.0,
        valorFinal: 2688.00,
      ),
      ItemCampanha(
        codigo: "BRKITNDT75",
        quantidade: 1,
        descricao: "KIT ZIGOMA-S (GRÁTIS)",
        valorUnitario: 8493.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 03 implantes Zi com 53% de desconto",
    promocode: "4400559110",
    valorFinal: 1167.48,
    itens: [
      ItemCampanha(
        codigo: "180.502",
        quantidade: 3,
        descricao: "IMPLANTE DE ZIRCONIA 3.75X10",
        valorUnitario: 828.00,
        desconto: 53.0,
        valorFinal: 1167.48,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Neodent",
    titulo: "Compre 10 implantes e Ganhe 10 implantes + 3 brocas",
    promocode: "4400604910",
    valorFinal: 4170.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 10,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 4170.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 10,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "103.170",
        quantidade: 1,
        descricao: "BROCA LANCA PLUS (GRÁTIS)",
        valorUnitario: 135.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
];

final List<CampanhaPromocional> campanhasStraumann = [
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre 10 implantes BLX e 20 componentes com 37% de desconto",
    promocode: "4400677410",
    valorFinal: 18724.80,
    observacao: "Ganhe 50% de desconto no Kit BLX guiada + 1 caso SIAB",
    itens: [
      ItemCampanha(
        codigo: "061.4310",
        quantidade: 10,
        descricao: "Imp Bone LevX D3.75mm RB SLActive10mmRox",
        valorUnitario: 990.00,
        desconto: 37.0,
        valorFinal: 6237.00,
      ),
      ItemCampanha(
        codigo: "022.0102",
        quantidade: 20,
        descricao: "NC VB P/ COROA, Ø3.8 AH3.5 GH2 TAN",
        valorUnitario: 228.00,
        desconto: 37.0,
        valorFinal: 2872.80,
      ),
      ItemCampanha(
        codigo: "BRKITSTR50",
        quantidade: 1,
        descricao: "CASSETE BLX GUIDE FULL ATÉ 4,5",
        valorUnitario: 19230.00,
        desconto: 50.0,
        valorFinal: 9615.00,
      ),
      ItemCampanha(
        codigo: "DS.SIAB.PGPR3",
        quantidade: 1,
        descricao: "Plan + Guia + Prov até 3 implantes (GRÁTIS)",
        valorUnitario: 575.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre 10 implantes BLT SLActive com 35% de desconto",
    promocode: "4400677510",
    valorFinal: 13628.65,
    observacao: "Ganhe 1 kit BLT Guiado com 45% de desconto",
    itens: [
      ItemCampanha(
        codigo: "021.5308",
        quantidade: 10,
        descricao: "BLT Ø4.1MM RC, SLACTIVE® 8MM, TIZR, NTP",
        valorUnitario: 746.00,
        desconto: 35.0,
        valorFinal: 4849.00,
      ),
      ItemCampanha(
        codigo: "BRKITSTR46",
        quantidade: 1,
        descricao: "KIT GUIDE BLT",
        valorUnitario: 15963.00,
        desconto: 45.0,
        valorFinal: 8779.65,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre 10 implantes BLC SLActive com 25% de desconto",
    promocode: "4400677610",
    valorFinal: 7425.00,
    observacao: "Ganhe brocas de perfil (para quem tem KIT BLX)",
    itens: [
      ItemCampanha(
        codigo: "035.9212S",
        quantidade: 10,
        descricao: "BLC Ø3.75mm RB, SLActive® 12mm RXD",
        valorUnitario: 990.00,
        desconto: 25.0,
        valorFinal: 7425.00,
      ),
      ItemCampanha(
        codigo: "034.362",
        quantidade: 1,
        descricao: "BLC/TLC Broca perf.,S,FIBA,Ø3.3,L27,SST (GRÁTIS)",
        valorUnitario: 391.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "034.363",
        quantidade: 1,
        descricao: "BLC/TLC Broca perf,S,FIBA,Ø3.75,L26,SST (GRÁTIS)",
        valorUnitario: 391.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre 6 implantes com 33% de desconto",
    promocode: "4400672710",
    valorFinal: 2998.92,
    itens: [
      ItemCampanha(
        codigo: "021.5308",
        quantidade: 6,
        descricao: "BLT Ø4.1MM RC, SLACTIVE® 8MM, TIZR, NTP",
        valorUnitario: 746.00,
        desconto: 33.0,
        valorFinal: 2998.92,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre R\$ 20k em implantes e componentes com 38% de desconto",
    promocode: "4400677710",
    valorFinal: 19859.84,
    observacao: "Ganhe 1 mochila de presente",
    itens: [
      ItemCampanha(
        codigo: "035.9008S",
        quantidade: 22,
        descricao: "BLC Ø3.3mm RB, SLActive® 8mm RXD",
        valorUnitario: 990.00,
        desconto: 38.0,
        valorFinal: 13503.60,
      ),
      ItemCampanha(
        codigo: "062.4733S",
        quantidade: 22,
        descricao: "RB/WB Pilar apar ang 17D4.6mm,GH3.5mmTAN",
        valorUnitario: 466.00,
        desconto: 38.0,
        valorFinal: 6356.24,
      ),
      ItemCampanha(
        codigo: "MOCHILA",
        quantidade: 1,
        descricao: "Mochila Straumann (GRÁTIS)",
        valorUnitario: 0.00,
        desconto: 0.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre R\$ 10.000 em componentes protéticos e ganhe 35% de desconto",
    promocode: "4400677810",
    valorFinal: 6715.80,
    itens: [
      ItemCampanha(
        codigo: "064.4362",
        quantidade: 20,
        descricao: "RB/WB Pilar prov coroa D3.8mm GH1.5mmTAN",
        valorUnitario: 214.00,
        desconto: 35.0,
        valorFinal: 2782.00,
      ),
      ItemCampanha(
        codigo: "062.4934",
        quantidade: 20,
        descricao: "RB/WB Var coroa paraf D3.8mmGH1.5mmAH5.5",
        valorUnitario: 271.00,
        desconto: 35.0,
        valorFinal: 3523.00,
      ),
      ItemCampanha(
        codigo: "065.0014",
        quantidade: 4,
        descricao: "RB/WB Cop calc var cor D3.8mmAH5.5mmPOM",
        valorUnitario: 101.00,
        desconto: 35.0,
        valorFinal: 262.60,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Straumann",
    titulo: "Compre de 5 a 10 componentes protéticos e ganhe 30% de desconto",
    promocode: "4400678810",
    valorFinal: 1468.60,
    itens: [
      ItemCampanha(
        codigo: "064.4362",
        quantidade: 4,
        descricao: "RB/WB Pilar prov coroa D3.8mm GH1.5mmTAN",
        valorUnitario: 214.00,
        desconto: 30.0,
        valorFinal: 599.20,
      ),
      ItemCampanha(
        codigo: "062.4934",
        quantidade: 4,
        descricao: "RB/WB Var coroa paraf D3.8mmGH1.5mmAH5.5",
        valorUnitario: 271.00,
        desconto: 30.0,
        valorFinal: 758.80,
      ),
      ItemCampanha(
        codigo: "065.0014",
        quantidade: 1,
        descricao: "RB/WB Cop calc var cor D3.8mmAH5.5mmPOM",
        valorUnitario: 101.00,
        desconto: 30.0,
        valorFinal: 70.70,
      ),
    ],
  ),
];

final List<CampanhaPromocional> campanhasEnterprise = [
  CampanhaPromocional(
    categoria: "Enterprise Solutions",
    titulo: "Compre 120 implantes GM Acqua + 120 intermediários com 55% de desconto",
    promocode: "4400674910",
    valorFinal: 38718.00,
    observacao: "Ganhe 1 motor NeoSurg com contra-ângulo (Exceto Oral Unic)",
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 120,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 55.0,
        valorFinal: 22518.00,
      ),
      ItemCampanha(
        codigo: "115.252",
        quantidade: 120,
        descricao: "MINI PILAR CON.ANG.GM EXACT 30°ALT.1.5",
        valorUnitario: 300.00,
        desconto: 55.0,
        valorFinal: 16200.00,
      ),
      ItemCampanha(
        codigo: "Y1003448",
        quantidade: 1,
        descricao: "KIT MOTOR NEODENT",
        valorUnitario: 11025.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Enterprise Solutions",
    titulo: "Compre 25 implantes GM Acqua + 25 componentes ao preço do playbook",
    promocode: "4400448610",
    valorFinal: 8107.65,
    observacao: "Ganhe KIT Cirúrgico Compacto GM (Clientes novos - Exceto Oral Unic)",
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 25,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 58.2,
        valorFinal: 4357.65,
      ),
      ItemCampanha(
        codigo: "115.275",
        quantidade: 25,
        descricao: "MINI PILAR CONICO GM 17 PARAFUSO REM 1.5",
        valorUnitario: 300.00,
        desconto: 50.0,
        valorFinal: 3750.00,
      ),
      ItemCampanha(
        codigo: "110.303",
        quantidade: 1,
        descricao: "KIT CIRURGICO COMPACTO HELIX GM COMPLETO",
        valorUnitario: 5818.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
];

final List<CampanhaPromocional> campanhasBiomateriais = [
  CampanhaPromocional(
    categoria: "Biomateriais",
    titulo: "A partir de 5 unidades de bio com 35%",
    promocode: "4400110906",
    valorFinal: 1196.00,
    itens: [
      ItemCampanha(
        codigo: "AW-1510",
        quantidade: 5,
        descricao: "STRAUMANN© CERABONE© 0,5-1,0MM, 1X0,5ML",
        valorUnitario: 368.00,
        desconto: 35.0,
        valorFinal: 1196.00,
      ),
    ],
  ),
];

final List<CampanhaPromocional> campanhasEshop = [
  CampanhaPromocional(
    categoria: "Eshop",
    titulo: "Compre 20 implantes com 50% de desconto e ganhe 1 brinde",
    promocode: "",
    valorFinal: 8340.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 0.0,
        valorFinal: 8340.00,
      ),
      ItemCampanha(
        codigo: "140.943",
        quantidade: 20,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA (GRÁTIS)",
        valorUnitario: 417.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Eshop",
    titulo: "Compre 15 implantes com 40% e ganha uma Luminária SMART",
    promocode: "",
    valorFinal: 3753.00,
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 15,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 40.0,
        valorFinal: 3753.00,
      ),
      ItemCampanha(
        codigo: "LUMINARIA",
        quantidade: 1,
        descricao: "Luminária SMART (GRÁTIS)",
        valorUnitario: 127.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Eshop",
    titulo: "A partir de 5 implantes com 30% de desconto",
    promocode: "440116506",
    valorFinal: 2611.00,
    itens: [
      ItemCampanha(
        codigo: "021.5308",
        quantidade: 5,
        descricao: "BLT Ø4.1MM RC, SLACTIVE® 8MM, TIZR, NTP",
        valorUnitario: 746.00,
        desconto: 30.0,
        valorFinal: 2611.00,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Eshop",
    titulo: "A partir de 10 implantes com 32% de desconto",
    promocode: "440116606",
    valorFinal: 5072.80,
    itens: [
      ItemCampanha(
        codigo: "021.5308",
        quantidade: 10,
        descricao: "BLT Ø4.1MM RC, SLACTIVE® 8MM, TIZR, NTP",
        valorUnitario: 746.00,
        desconto: 32.0,
        valorFinal: 5072.80,
      ),
    ],
  ),
];

final List<CampanhaPromocional> campanhasCursos = [
  CampanhaPromocional(
    categoria: "Cursos",
    titulo: "Kit Completo para Curso + Brinde Exclusivo",
    promocode: "4400445810",
    valorFinal: 11625.66,
    observacao: "Compre um Kit Cirúrgico Protético + Motor + Implantes + Biomaterial e ganhe um brinde exclusivo",
    itens: [
      ItemCampanha(
        codigo: "BRKITNDT54",
        quantidade: 1,
        descricao: "KIT CIR. COMPACTO GM",
        valorUnitario: 5983.00,
        desconto: 82.0,
        valorFinal: 1076.94,
      ),
      ItemCampanha(
        codigo: "BRKITNDT76",
        quantidade: 1,
        descricao: "BRKIT Protetico GM/HE",
        valorUnitario: 2804.00,
        desconto: 82.0,
        valorFinal: 504.72,
      ),
      ItemCampanha(
        codigo: "Y1003448",
        quantidade: 1,
        descricao: "KIT MOTOR NEODENT",
        valorUnitario: 11025.00,
        desconto: 30.0,
        valorFinal: 7717.50,
      ),
      ItemCampanha(
        codigo: "109.943",
        quantidade: 10,
        descricao: "IMPLANTE HELIX GM 3.5X8",
        valorUnitario: 382.00,
        desconto: 60.0,
        valorFinal: 1528.00,
      ),
      ItemCampanha(
        codigo: "AW-1510",
        quantidade: 1,
        descricao: "STRAUMANN© CERABONE© 0,5-1,0MM, 1X0,5ML",
        valorUnitario: 368.00,
        desconto: 35.0,
        valorFinal: 239.20,
      ),
    ],
  ),
];

final List<CampanhaPromocional> campanhasFinanciamento = [
  CampanhaPromocional(
    categoria: "Financiamento",
    titulo: "Compre 380 implantes GM Acqua c/ 55% de desconto",
    promocode: "4400445810",
    valorFinal: 71307.00,
    observacao: "Ganhe 12 Kits Cirúrgicos Compactos",
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 380,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 55.0,
        valorFinal: 71307.00,
      ),
      ItemCampanha(
        codigo: "BRKITNDT54",
        quantidade: 12,
        descricao: "KIT CIR. COMPACTO GM (GRÁTIS)",
        valorUnitario: 5983.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Financiamento",
    titulo: "Compre 510 implantes GM Acqua c/ 55% de desconto",
    promocode: "4400603310",
    valorFinal: 95701.50,
    observacao: "Ganhe 12 Kits cirúrgicos compactos e 12 Kits protéticos",
    itens: [
      ItemCampanha(
        codigo: "140.943",
        quantidade: 510,
        descricao: "IMPLANTE HELIX GM 3.5X8 ACQUA",
        valorUnitario: 417.00,
        desconto: 55.0,
        valorFinal: 95701.50,
      ),
      ItemCampanha(
        codigo: "BRKITNDT54",
        quantidade: 12,
        descricao: "KIT CIR. COMPACTO GM (GRÁTIS)",
        valorUnitario: 5983.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
      ItemCampanha(
        codigo: "BRKITNDT76",
        quantidade: 12,
        descricao: "BRKIT Protetico GM/HE (GRÁTIS)",
        valorUnitario: 2804.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
  CampanhaPromocional(
    categoria: "Financiamento",
    titulo: "Compre R\$ 50k em componentes c/ 55% de desconto",
    promocode: "4400603410",
    valorFinal: 50166.00,
    observacao: "Ganhe 12 kits protéticos (aprox. 260 unidades intermediários)",
    itens: [
      ItemCampanha(
        codigo: "115.275",
        quantidade: 260,
        descricao: "MINI PILAR CONICO GM 17 PARAFUSO REM 1.5",
        valorUnitario: 300.00,
        desconto: 55.0,
        valorFinal: 35100.00,
      ),
      ItemCampanha(
        codigo: "108.022",
        quantidade: 120,
        descricao: "TRANSFER MINI P.CONICO MOLD.ABERTA 4.1",
        valorUnitario: 59.00,
        desconto: 55.0,
        valorFinal: 3186.00,
      ),
      ItemCampanha(
        codigo: "118.305",
        quantidade: 120,
        descricao: "CILIN.PROVISORIO MUN.UNIV.CLICK 3.3X6",
        valorUnitario: 30.00,
        desconto: 55.0,
        valorFinal: 1620.00,
      ),
      ItemCampanha(
        codigo: "BRKITNDT76",
        quantidade: 12,
        descricao: "BRKIT Protetico GM/HE (GRÁTIS)",
        valorUnitario: 2804.00,
        desconto: 100.0,
        valorFinal: 0.00,
        isGratis: true,
      ),
    ],
  ),
];
